<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260925000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema: users, authentication servers, applications, settings, service checks and updates';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE application (id UUID NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, token_hash VARCHAR(64) NOT NULL, token_hint VARCHAR(16) NOT NULL, can_impersonate BOOLEAN NOT NULL, enabled BOOLEAN NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A45BDDC1B3BC57DA ON application (token_hash)');
        $this->addSql('CREATE TABLE authentication_server (id UUID NOT NULL, name VARCHAR(120) NOT NULL, type VARCHAR(16) NOT NULL, enabled BOOLEAN NOT NULL, url VARCHAR(255) NOT NULL, internal_url VARCHAR(255) DEFAULT \'\' NOT NULL, client_id VARCHAR(255) DEFAULT \'\' NOT NULL, client_secret TEXT DEFAULT \'\' NOT NULL, scopes VARCHAR(255) DEFAULT \'openid email profile\' NOT NULL, link_existing_accounts BOOLEAN DEFAULT false NOT NULL, start_tls BOOLEAN NOT NULL, base_dn VARCHAR(512) NOT NULL, bind_dn VARCHAR(512) NOT NULL, bind_password TEXT NOT NULL, user_filter TEXT NOT NULL, admin_group_dn VARCHAR(512) NOT NULL, attributes JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE service_check (id VARCHAR(120) NOT NULL, status VARCHAR(20) NOT NULL, detail TEXT NOT NULL, latency_ms DOUBLE PRECISION DEFAULT NULL, checked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_ok_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, failing_since TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE setting (name VARCHAR(100) NOT NULL, value JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, PRIMARY KEY (name))');
        $this->addSql('CREATE TABLE update_run (id UUID NOT NULL, method VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, from_version VARCHAR(80) NOT NULL, target VARCHAR(80) DEFAULT NULL, log TEXT NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8711D9A37B00651C ON update_run (status)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, source VARCHAR(16) NOT NULL, ldap_dn VARCHAR(512) DEFAULT NULL, external_id VARCHAR(255) DEFAULT NULL, ldap_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by VARCHAR(180) DEFAULT NULL, updated_by VARCHAR(180) DEFAULT NULL, authentication_server_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_external_id ON "user" (authentication_server_id, external_id)');
        $this->addSql('CREATE INDEX IDX_8D93D649C2F36C49 ON "user" (authentication_server_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649C2F36C49 FOREIGN KEY (authentication_server_id) REFERENCES authentication_server (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649C2F36C49');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE authentication_server');
        $this->addSql('DROP TABLE service_check');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP TABLE update_run');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
